# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
commons-math3 = "3.6.1"
groovy = "4.0.28"
guava = "33.4.6-jre"
junit = "4.13.2"
spock-core = "2.3-groovy-4.0"

[libraries]
commons-math3 = { module = "org.apache.commons:commons-math3", version.ref = "commons-math3" }
groovy = { module = "org.apache.groovy:groovy", version.ref = "groovy" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit = { module = "junit:junit", version.ref = "junit" }
spock-core = { module = "org.spockframework:spock-core", version.ref = "spock-core" }
